### ISSUE TITLE
Not able to load the projects for the CSharp-GradeBookApplication

### ISSUE THREAD

**Issue by kalapakim** [pluralsight-projects/CSharp-GradeBookApplication#28]
When I try to open the .sln file, the GradeBook project shows (load failed) and the GradebookTests shows (unavailable)...I ran git fetch, git pull to make sure I got everything from Master. Still no good.

**Comment by EricJFisher** [comment]
Hello @kalapakim 

I just pulled a fresh copy on both Visual Studio 2017 Community for OSX and Visual Studio 2017 Community on Windows 10. (both worked properly for me)

I'm listing a number of things you might try to resolve this issue, if they don't work (or don't match what you're seeing) please attach a screen shot where I can see both what version of Visual Studio you are using and what error/notification you're seeing.

Some things to try.

- Run the Visual Studio Installer and make sure .NET Core is checked in your options. (where you'll find this depends on which version of Visual Studio is running, if this is not checked the project will not load. The video showing you how to install Visual Studio will show this, it's available on the project on Pluralsight's website under the Setup task)

- Make sure Visual Studio is fully up to date with the latest version. (typically you'll see the flag in the top right light up when there is updates, but you can update manually as well) I've found sometimes in the past if someone on my team is using a newer update than I am it can cause the project / solution to complain.

- Depending on how the IDE presents the solution after it fails to load. (Usually one or more projects will show as "unable to load", "incompatible", etc) often simply right clicking and choosing "reload" or "unload" then "reload" will resolve it. (I've seen this happen on the rare occasion when opening a project of a type I've never opened before)

- If you are fully up to date and still having a problem the next thing to check would be in git to see if there are any differences in the sln and csproj files on your local machine vs the original repo. (I've had extensions in the past quietly alter solution and project files, usually in ways that used to make sense, but causes problems in the new format.)

- If you're using Visual Studio 2015, I believe it's tooling is not up to date with the latest version of .NET Core and may not be compatible. (need to confirm) If you're using an IDE other than Visual Studio please try Visual Studio is it could be that IDE is not yet updated to the latest .Net Core tooling.

**Comment by EricJFisher** [comment]
Closing this issue as it appears to be isolated, if you're still having problems feel free to add to the issue.
